"""init

Revision ID: 0e2d4c834a0e
Revises: 
Create Date: 2020-05-16 19:52:53.898843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e2d4c834a0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tesera_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('en_name', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('bgg_rating', sa.Float(), nullable=True),
    sa.Column('min_players', sa.SmallInteger(), nullable=True),
    sa.Column('min_players_recommended', sa.SmallInteger(), nullable=True),
    sa.Column('max_players', sa.SmallInteger(), nullable=True),
    sa.Column('max_players_recommended', sa.SmallInteger(), nullable=True),
    sa.Column('play_time_min', sa.SmallInteger(), nullable=True),
    sa.Column('play_time_max', sa.SmallInteger(), nullable=True),
    sa.Column('tesera_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('en_name'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('tesera_id')
    )
    op.create_table('game_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tesera_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('tesera_id')
    )
    op.create_table('category_game_mtm',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_category_tesera_id', sa.Integer(), nullable=True),
    sa.Column('game_tesera_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_category_tesera_id'], ['game_category.tesera_id'], ),
    sa.ForeignKeyConstraint(['game_tesera_id'], ['game.tesera_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_category_tesera_id', 'game_tesera_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_game_mtm')
    op.drop_table('game_category')
    op.drop_table('game')
    # ### end Alembic commands ###
