"""Add tesera_id field to category

Revision ID: 4cedfe4e7d29
Revises: b20c27c87b7e
Create Date: 2020-05-08 17:33:01.389612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cedfe4e7d29'
down_revision = 'b20c27c87b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_category', sa.Column('tesera_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'game_category', ['tesera_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_category', type_='unique')
    op.drop_column('game_category', 'tesera_id')
    # ### end Alembic commands ###
