"""Change mtm

Revision ID: ba48a60c6455
Revises: 4cedfe4e7d29
Create Date: 2020-05-11 15:01:21.501538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba48a60c6455'
down_revision = '4cedfe4e7d29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_game_mtm', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category_game_mtm', 'id')
    # ### end Alembic commands ###
